services:
  web:
    build:
      context: /srv/sev  # Абсолютен път към директорията
    ports:
      - "5000:5000"
    volumes:
      - /srv/sev:/app
    environment:
      - FASTAPI_ENV=development
